pull_request_rules:
  - name: Approve and merge autobump PRs if tests are successful
    conditions:
      - "author=BiocondaBot"
      - "label=autobump"
      - "created-at>=3 days ago"
      - "check-success=bioconda.bioconda-recipes"
      - "#commits=1"
    actions:
      review:
        type: APPROVE
        message: Automatically approving successfull autobump
      merge:
        method: squash