{% set name = "PyEnsembl" %}
{% set version = "2.2.6" %}
{% set sha256 = "ccffda6dde7041fe2e44dbe94471653a051ac8025647eda93d516c7921f94c1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyensembl = pyensembl.shell:run

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - typechecks >=0.0.2
    - numpy >=1.7
    - pandas >=0.15
    - datacache >=1.1.4
    - memoized-property >=1.0.2
    - six >=1.9.0
    - gtfparse >=1.3.0
    - serializable
    - tinytimer
    - pylint >=1.4.4
    - python-dateutil >=2.5.0

test:
  imports:
    - pyensembl
  commands:
    - pyensembl --help

about:
  home: https://github.com/openvax/pyensembl
  license: Apache-2.0
  summary: 'Python interface to ensembl reference genome metadata'
  license_family: Apache
  license_file: LICENSE
