{% set version = "1.8.1" %}
{% set sha256 = "542fa1574622e04f72532fa8b3630e51224f9f7d708b7501625ecbbe69d5f6c6" %}

package:
  name: python-newick
  version: '{{version}}'

source:
  url: https://pypi.io/packages/source/n/newick/newick-{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - newick

about:
  home: https://github.com/glottobank/python-newick
  license: Apache-2.0
  summary: A python module to read and write the Newick format
  license_family: Apache

extra:
  recipe-maintainers:
    - nickp60
