{% set version = "1.7.1" %}
{% set sha256 = "72b0d11993b1d73d5cb80631aac194d7e9453f5d712014ca37caf17a8d89c780" %}

package:
  name: python-newick
  version: '{{version}}'

source:
  url: https://pypi.io/packages/source/n/newick/newick-{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - newick

about:
  home: https://github.com/glottobank/python-newick
  license: Apache-2.0
  summary: A python module to read and write the Newick format
  license_family: Apache

extra:
  recipe-maintainers:
    - nickp60
