{% set version = "0.14.2" %}
{% set sha256 = "a5909065072b1efc81602c5f151c7b28813227047b0bbc7c7a81eeb79950e842" %}

package:
  name: isatools
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/i/isatools/isatools-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - isatools = isatools:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - jsonschema
    - pandas
    - networkx
    - lxml
    - requests
    - chardet
    - iso8601
    - jinja2
    - beautifulsoup4
    - mzml2isa
    - biopython
    - progressbar2
    - pyyaml

test:
  imports:
    - isatools
    - isatools.convert
    - isatools.create
    - isatools.errors
    - isatools.io
    - isatools.net

about:
  home: https://github.com/ISA-tools/isa-api
  license: CPAL
  license_family: OTHER
  summary: Metadata tracking tools help to manage an increasingly diverse set of life science, environmental and biomedical
    experiments
