{% set name = "OakVar" %}
{% set version = "2.8.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oakvar-{{ version }}.tar.gz
  sha256: 38d4c05d2bf768961677a72bb5bc5fc18dacfea62b252ec586a6d9696eec6deb

build:
  number: 0
  entry_points:
    - ov=oakvar.cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - aiohttp
    - aiohttp-cors
    - aiosqlite
    - chardet
    - connectorx
    - download
    - gdown
    - intervaltree
    - markdown
    - mpmath
    - nest-asyncio
    - oyaml
    - packaging
    - Pillow
    - polars
    - psutil
    - pyarrow
    - pyjwt
    - pyliftover
    - python
    - python-dateutil
    - requests
    - requests-toolbelt
    - python-duckdb
    - rich
    - twobitreader

test:
  imports:
    - oakvar
  requires:
    - python
    - pip

about:
  home: "http://www.oakvar.com"
  summary: "OakVar - Genomic Variant Analysis Platform"
  dev_url: https://docs.oakvar.com
  doc_url: https://docs.oakvar.com
  license_file: LICENSE
  license: AGPL v3
  license_family: GPL

extra:
  recipe-maintainers:
    - rkimoakbioinformatics
