{% set version = "0.3.20" %}

package:
  name: pybigwig
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/e2/18/eb175e8a15ae2822ffdab1e666dc8d081b1245e1064f2b36033af0076f3e/pyBigWig-0.3.20.tar.gz
  sha256: ba63ffb302647a6bcda75187a9d8576bb249e37ae6e83379ddb31e22cd7a8c0b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - curl
    - libcurl
    - zlib
    - numpy
  run:
    - python
    - libcurl
    - zlib
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyBigWig
  commands:
    - python -c "import pyBigWig; assert(pyBigWig.numpy == 1); assert(pyBigWig.remote == 1)"

about:
  home: https://github.com/dpryan79/pyBigWig
  license: MIT
  summary: A python extension written in C for quick access to bigWig files.
