{% set version = "0.2.21" %}

package:
  name: bionumpy
  version: {{ version }}

source:
  url: https://github.com/bionumpy/bionumpy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0516d9f193d8db32d56c4de4ea96b235c0f0e29f4c61195a1cac6f9c57f8f395
  
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3
    - zlib
    - pip
  run:
    - python >=3
    - numpy >=1.20,<1.24
    - npstructures >=0.2.9

test:
  imports:
    - bionumpy


about:
  home: https://github.com/bionumpy/bionumpy
  license: MIT
  summary: "Library for working with biological sequence data as numpy arrays"
  
extra:
  recipe-maintainers:
    - telatin
