{% set version = "4.0.0" %}
{% set hash = "11732baaf14f7027b6b0a82e3ef3e79387f8312d43a53e351cd7b9c0c91e62f6" %}

package:
  name: truvari
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

source:
  url: https://files.pythonhosted.org/packages/18/c2/eb61fda484af82ec5efeea1951ecab2b90abd0ffa59a6e2899a888ffd27e/Truvari-4.0.0.tar.gz
  sha256: {{ hash }}

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytabix
    - bwapy
    - pandas
    - python-levenshtein ==0.12.2
    - python-edlib >=1.3.8.post2
    - progressbar2 >=3.41.0
    - pysam >=0.15.2
    - intervaltree >=3.0.2
    - joblib >=1.0.1
    - numpy >=1.21.2
    - pytabix >=0.1
    - bwapy >=0.1.4
    - pandas >=1.3.3

test:
  commands:
    - truvari --help

about:
  home: https://github.com/ACEnglish/truvari
  license: MIT
  summary: 'Structural variant comparison tool for VCFs'
