{% set name = "querynator" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 257780e9232a95fe5c12f1e90adf1cfbafc0b4b34786ad01c0d4e1e5a2ed8491

build:
  number: 0
  noarch: python
  entry_points:
    - querynator=querynator.__main__:run_querynator
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python =3.8
    - pip
  host:
    - civicpy =3.0.0
    - click >=8.1.3
    - httplib2
    - numpy
    - pandas
    - pip
    - pysam >=0.20.0
    - pytest >=6.2.4
    - python
    - requests
    - requests-cache
    - sphinx >=5.3.0
    - sphinx-rtd-theme
  run:
    - civicpy =3.0.0
    - click >=8.1.3
    - httplib2
    - numpy
    - pandas
    - pysam >=0.20.0
    - pytest >=6.2.4
    - python
    - requests
    - requests-cache
    - sphinx >=5.3.0
    - sphinx-rtd-theme

test:
  imports:
    - querynator
    - querynator.query_api
    - tests
  commands:
    - querynator --help
  requires:
    - pytest >=3

about:
  home: "https://github.com/qbic-pipelines/querynator"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python package to query cancer variant databases"
  doc_url: "https://querynator.readthedocs.io/"
  dev_url: "https://github.com/qbic-pipelines/querynator/tree/dev"

extra:
  recipe-maintainers:
    - SusiJo
    - mapo9
  identifiers:
    - biotools:querynator
