{% set name = "indextools" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: bfba993dfb0ea2cf00b6f8abdcc5972e517ff9ae727e3da984db8e880a7240b3

build:
  number: 0
  noarch: python
  entry_points:
    - indextools = indextools.console:indextools
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - autoclick >=0.6.1
    - loguru >=0.3.2
    - ngsindex >=0.1.7
    - pip
    - poetry
    - pysam >=0.15
    - python
    - xphyle >=4.1.3
  run:
    - autoclick >=0.6.1
    - loguru >=0.3.2
    - ngsindex >=0.1.7
    - pysam >=0.15
    - python
    - xphyle >=4.1.3

test:
  imports:
    - cgranges
    - indextools
  commands:
    - indextools --help

about:
  home: "https://github.com/dnanexus/indextools"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A toolkit for accelerating genomics using index files."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - matthdsm
