{% set name = "pybbi" %}
{% set version = "0.3.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "406383981c80481d8aa86499681442a20e68bdc7ef3806cfd6cc4492d3f363e1"

build:
  number: 0
  skip: True  # [py2k or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools
    - pkgconfig
    - six
    - openssl
    - libpng
    - zlib
  run:
    - numpy
    - python
    - six
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - bbi

about:
  home: "https://github.com/nvictus/pybbi"
  license: "MIT"
  license_family: "MIT"
  summary: "Python bindings to UCSC Big Binary (bigWig/bigBed) file library"

extra:
  recipe-maintainers:
    - Nanguage
