{% set name = "cogent3" %}
{% set version = "2023.2.12a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cogent3-{{ version }}.tar.gz
  sha256: 387053bfcb0c4b43b9cd2bbf7e7272ee2392bb17d36e6d4240540b8dacb6fd2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3
    - pip
    - flit-core
  run:
    - python >=3
    - chardet
    - numpy
    - numba >0.48.0
    - scitrack
    - tqdm
    - tinydb

test:
  imports:
    - cogent3

about:
  home: https://pypi.org/project/cogent3/
  summary: 'COmparative GENomics Toolkit 3: genomic sequence analysis within notebooks or on compute systems with 1000s of CPUs.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dpryan79
