{% set name = "selectFasta" %}
{% set version = "2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/andvides/selectFasta/archive/refs/tags/v2.1.tar.gz
  sha256: 8e33177a985c0a6d31acc17dcb9e7b2233ea8cfbddb9850c1c434b0f0bb5fcc1
  
build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    
test:
  commands:
    - selectFasta -h 2>&1 | grep "selectFasta" > /dev/null

about:
  home: https://github.com/andvides/selectFasta/
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: "FASTA or FASTQ select from a list of header names"
